version: '2'
services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.old
    volumes:
      - repositories:/home/server/repositories
    links:
      - memcached
      - mongo
    ports:
      - "80:8080"
  mongo:
    image: mongo
    ports:
      - "27017"
    volumes:
      - dbdata:/data/db
  memcached:
    image: memcached:alpine
    ports:
      - "11211"
volumes:
  repositories:
    driver: local
  dbdata:
    driver: local